# Generated by Django 3.0.3 on 2020-03-14 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_auto_20200314_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remainder',
            options={'verbose_name_plural': 'Remainder'},
        ),
        migrations.AlterField(
            model_name='remainder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
