# Generated by Django 3.0.3 on 2020-03-14 18:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200314_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainder',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 16, 18, 23, 12, 215803, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
