# Generated by Django 3.0.3 on 2020-03-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remainder_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainder',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
