# Generated by Django 3.0.3 on 2020-03-21 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sem2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m2', models.CharField(max_length=20)),
                ('ds_c', models.CharField(max_length=20)),
                ('ec', models.CharField(max_length=20)),
                ('ed', models.CharField(max_length=20)),
                ('em', models.CharField(max_length=20)),
                ('es', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sem1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m1', models.CharField(max_length=1)),
                ('ppsc', models.CharField(max_length=1)),
                ('ep', models.CharField(max_length=1)),
                ('bee', models.CharField(max_length=1)),
                ('eng', models.CharField(max_length=1)),
                ('es', models.CharField(max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
